spring.application.name: demo

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true